[build]
  command = "next build"
  publish = ".next"

[context.production.environment]
  JWT_SECRET = "your_secure_jwt_secret_key_here_must_be_at_least_32_chars_long"

[[plugins]]
  package = "@netlify/plugin-nextjs"